### ISSUE TITLE
Derive MapShed values from Raster Datasets

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/mmw-geoprocessing#27]
Using the GMS File Key, and the ingested Raster Datasets, derive values used by MapShed and return them via `MapshedJob`.

These values are derived purely from Raster datasets that are currently available, namely NLCD,  Hydrological Soil Groups, and Available Water Holding Capacity:
- Landuse(l)
- LuArea(l)
- NormalSys
- n23
- n23b
- n24
- n24b
- CN(l)
- AvgAwc

Either derive these values completely in the geoprocessing unit, or identify the common intermediate values used to derive these values and respond with them instead, so that we make as few calls to the geoprocessing unit as possible.

**Comment by jamesmcclain** [comment]
I made a few more changes.  After having slept on the issue, I realized that we were also doing a whole lot of extra allocation in the inner loop.  (Please see https://github.com/jamesmcclain/mmw-geoprocessing/commit/0784dab3de31ee1e78735a08f8f545e921a5dd99 and https://github.com/jamesmcclain/mmw-geoprocessing/commit/8e9b4805326e4908f427ae20f43092137f0c6cc7 .)

**Comment by rajadain** [comment]
-3 for https://github.com/WikiWatershed/model-my-watershed/issues/1258

**Comment by rajadain** [comment]
This should be closed in favor of
- https://github.com/WikiWatershed/model-my-watershed/issues/1272
- https://github.com/WikiWatershed/model-my-watershed/issues/1273
- https://github.com/WikiWatershed/model-my-watershed/issues/1274
- https://github.com/WikiWatershed/model-my-watershed/issues/1275
- https://github.com/WikiWatershed/model-my-watershed/issues/1276
- https://github.com/WikiWatershed/model-my-watershed/issues/1277
