### ISSUE TITLE
Collections API: Upgrade GeoTrellis

### ISSUE THREAD

**Issue by rajadain** [WikiWatershed/mmw-geoprocessing#49]
Upgrade GeoTrellis dependency to latest (1.1.1 as of this writing).

If the `summary` project causes problems during the upgrade, consider disabling it. Ideally we could have `api` and `summary` require different versions of GeoTrellis, but I'm not sure if sbt allows that.

Depends on #48

**Comment by kellyi** [comment]
We may also consider removing Spark Job Server here.
