### ISSUE TITLE
Precompute histograms

### ISSUE THREAD

**Issue by jamesmcclain** [WikiWatershed/mmw-geoprocessing#5]
Rather than recomputing histograms for tiles contained entirely within the AoI, we should consider pre-computing the histograms for groups of tiles.  Initially, I would like to suggest square groups composed of 2^(2i) tiles.

Since each tile is roughly 4k, this does not do much for small i.  However, for i >= 5 (or something like that) this would reduce the latency of the service for large areas of interest.  I would expect that if the AoI contains k tiles, this would reduce the number of things that need to be downloaded to ~ sqrt(k).  If a certain amount of inaccuracy can be tolerated, this could go down to ~ lg(k).

Of course, tiles that are intersected by the AoI boundary would still need to be downloaded.

**Comment by hectcastro** [comment]
I like the idea of precomputing these types of results. It would be interesting to bake common metadata for a tile, or a group of tiles, into the S3 objects themselves using [object metadata](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-metadata).

**Comment by jamesmcclain** [comment]
If groups of tiles can have metadata associated with them and the metadata can be easily accessed without downloading the tiles, that might be an easy way forward.

Also I just want to say: what is written above is just a suggestion, comments and criticisms (about particulars or the idea in general) are welcomed.

**Comment by jamesmcclain** [comment]
Is it okay to close this issue?  There is a Geotrellis issue mirroring this.
