### ISSUE TITLE
Reuse downloaded tiles

### ISSUE THREAD

**Issue by jamesmcclain** [WikiWatershed/mmw-geoprocessing#7]
The code takes an array of (multi)polygons as input and calculates the censuses of all of them.  If we assume that all polygons after the first are contained within the area of the first one, there is no need to re-download tiles for all of the polygons after the first one.

**Comment by jamesmcclain** [comment]
~~Actually it appears that this has already been fixed!  (reducing to zero points).~~

**Comment by jamesmcclain** [comment]
I hope it doesn't mess anything up, but I am moving this back to one point.  (It started as 2, then I thought it was already done and reduced it to 0, then I realized it wasn't done and moved it to 1.)

**Comment by caseycesari** [comment]
@jamesmcclain Generally, if it was already done, moving the points elsewhere is fine, but we tend to keep the original estimate. Sometimes we estimate over, sometimes under.

**Comment by jamesmcclain** [comment]
@caseypt I had consulted with @mmcfarland about reducing the points.  I put that comment there after I restored the point and before I realized that it was waffle that removed it.

**Comment by caseycesari** [comment]
Cool. Sounds good.
