### ISSUE TITLE
Collections API: Release 3.0.0

### ISSUE THREAD

**Issue by kellyi** [WikiWatershed/mmw-geoprocessing#76]
We're currently at 3.0.0-beta-2 but in advance of the next MMW release we should release 3.0.0

May be worthwhile also to do this in tandem with https://github.com/WikiWatershed/mmw-geoprocessing/issues/56

**Comment by rajadain** [comment]
~~3.0.0-beta-2~~ [3.0.0-beta-3](https://github.com/WikiWatershed/mmw-geoprocessing/releases/tag/3.0.0-beta-3)

**Comment by rajadain** [comment]
We should try and do this before the November [1.21.0](https://github.com/WikiWatershed/model-my-watershed/milestone/58) release, since we missed this in 1.20.0.

**Comment by rajadain** [comment]
Done in https://github.com/WikiWatershed/mmw-geoprocessing/commit/efa54bf4f430e3fa25166ef98504910f210838de
