### ISSUE TITLE
Compute Analysis results of all known AoI boundaries

### ISSUE THREAD

**Issue by mmcfarland** [WikiWatershed/mmw-geoprocessing#8]
By computing the results of known Areas (Boundary selections) we can avoid running an on-the-fly geoprocessing request.  This may be even more useful as we add additional layers to the analysis output beyond soils and nlcd.  Work on #5, would also speed up arbitrary sized areas as well.

**Comment by kellyi** [comment]
For well known areas of interest we're now caching their geoprocessing results in MMW. Arbitrary aois still kick off a new geoprocessing run, but the service is now faster after moving to akka-http & the collections API.
